server:
  port: 9191
  servlet:
    context-path: /api/v1
spring:
  application:
    name: ORDER-SERVICE
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    url: jdbc:h2:mem:order_db
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true
  config:
    import: configserver:http://localhost:9196
  zipkin:
    base-url: http://localhost:9411/
logging:
  file:
    name: order-service.log